package envfile

import (
	"os"
	"strings"

	"github.com/ldhnam/envigator/internal/secrets"
)

// BuildExampleTemplate generates a sanitized .env.example from the primary
// .env in dir. Comments are preserved, and secret-like values are replaced
// with <YOUR_KEY> placeholders.
func BuildExampleTemplate(dir string) (string, error) {
	paths, err := Discover(dir)
	if err != nil {
		return "", err
	}
	prim := Primary(paths)
	if prim == "" {
		return "", nil
	}
	data, err := os.ReadFile(prim)
	if err != nil {
		return "", err
	}
	var out []string
	out = append(out, "# Generated by envigator — copy to .env and fill in the values", "")
	lines := strings.Split(string(data), "\n")
	for i := 0; i < len(lines); i++ {
		line := lines[i]
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, ";") {
			out = append(out, line)
			continue
		}
		key, raw, ok := assignment(trimmed)
		if !ok {
			out = append(out, line)
			continue
		}
		if HasUnclosedQuote(raw) {
			val := raw
			j := i + 1
			for j < len(lines) && HasUnclosedQuote(val) {
				val += "\n" + lines[j]
				j++
			}
			out = append(out, renderTemplateLine(key, Unquote(val)))
			i = j - 1
			continue
		}
		out = append(out, renderTemplateLine(key, Unquote(raw)))
	}
	return strings.Join(out, "\n") + "\n", nil
}

// renderTemplateLine returns KEY=value or KEY=<YOUR_KEY>.
func renderTemplateLine(key, value string) string {
	if NeedsPlaceholder(key, value) {
		return key + "=<YOUR_" + key + ">"
	}
	return key + "=" + value
}

// needsPlaceholder reports whether a value should be masked: empty values,
// values matching a credential pattern, or keys whose name implies a secret.
func NeedsPlaceholder(key, value string) bool {
	if value == "" {
		return true
	}
	if len(secrets.Detect(value)) > 0 {
		return true
	}
	upper := strings.ToUpper(key)
	for _, marker := range []string{"SECRET", "TOKEN", "PASSWORD", "PASS", "KEY", "API", "PRIVATE", "CREDENTIAL"} {
		if strings.Contains(upper, marker) {
			return true
		}
	}
	return false
}

// assignment splits an assignment line into key and raw value.
func assignment(line string) (key, raw string, ok bool) {
	line = strings.TrimPrefix(strings.TrimSpace(line), "export ")
	line = strings.TrimSpace(line)
	i := strings.Index(line, "=")
	if i <= 0 {
		return "", "", false
	}
	key = strings.TrimSpace(line[:i])
	if !keyNameValid(key) {
		return "", "", false
	}
	return key, strings.TrimSpace(line[i+1:]), true
}
