package tui

import (
	"os"
	"path/filepath"
	"strings"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/ldhnam/envigator/internal/secrets"
)

// generateTemplate writes a sanitized .env.example from the primary .env,
// replacing secret-looking values with <YOUR_KEY> placeholders.
func (m Model) generateTemplate() (tea.Model, tea.Cmd) {
	if m.prim == "" {
		m.toastf("no primary .env to template")
		return m, toastCmd()
	}
	f := m.fileFor(m.prim)
	if f == nil || len(f.Values) == 0 {
		m.toastf("primary %s has no keys", m.primaryLabel())
		return m, toastCmd()
	}
	var lines []string
	lines = append(lines, "# Generated by envigator — copy to .env and fill in the values")
	lines = append(lines, "")
	for _, k := range f.Keys {
		if templateNeedsPlaceholder(k, f.Values[k]) {
			lines = append(lines, k+"=<YOUR_"+k+">")
		} else {
			lines = append(lines, k+"="+f.Values[k])
		}
	}
	path := filepath.Join(m.dir, ".env.example")
	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
		m.toastf("failed to write .env.example: %v", err)
		return m, toastCmd()
	}
	m.reload()
	m.toastf("generated .env.example (%d keys)", len(f.Values))
	return m, toastCmd()
}

// templateNeedsPlaceholder reports whether a value should be replaced with a
// <YOUR_KEY> placeholder: empty values, values that match a credential
// pattern, or keys whose name implies a secret.
func templateNeedsPlaceholder(key, val string) bool {
	if val == "" {
		return true
	}
	if len(secrets.Detect(val)) > 0 {
		return true
	}
	upper := strings.ToUpper(key)
	for _, marker := range []string{"SECRET", "TOKEN", "PASSWORD", "PASS", "KEY", "API", "PRIVATE", "CREDENTIAL"} {
		if strings.Contains(upper, marker) {
			return true
		}
	}
	return false
}
